### ISSUE TITLE
Crash when talking to Sariel "Data unsupported text character ' ' "

### ISSUE THREAD

**Issue by Winnetou11** [Pyrdacor/Ambermoon.net#201]
Crash when talking to Sariel in "Sylphenhöhle" "Data unsupported text character ' ' "
German data files version 1.07
Ambermoon.net version 1.0 (github.com/Pyrdacor/Ambermoon.net)
[Save.99.zip](https://github.com/Pyrdacor/Ambermoon.net/files/7123797/Save.99.zip)
ps://github.com/Pyrdacor/Ambermoon.net)

**Comment by fuckgithub42** [comment]
I can reproduce it by using the "schwester/sister" key word, with German 1.08 using my own savefile.

**Comment by Pyrdacor** [comment]
> I can reproduce it by using the "schwester/sister" key word, with German 1.08 using my own savefile.

You mean with Ambermoon.net or the original game on Amiga/Emulator?

**Comment by Pyrdacor** [comment]
Hm I can't reproduce this with the savegame provided. Not even with the german 1.07 data.

I am not aware of any change that affected text processing since 1.0 though.

Can you both please test with the following version?
https://github.com/Pyrdacor/Ambermoon.net/raw/master/Tests/Ambermoon.net.zip

**Comment by skdubg** [comment]
Its fixed in the files there a awaiting the pull request

**Comment by a1exh** [comment]
@Pyrdacor is this something that could have been caught with a small check in AmbermoonTextImport.exe?

**Comment by Pyrdacor** [comment]
I am still don't know what the error actually is. Maybe someone can clarify.

**Comment by skdubg** [comment]
There was a "/" in the text from Sariel
copy and paste mistake by me. Sorry

**Comment by Pyrdacor** [comment]
Ok I will release a new original game version asap.

**Comment by Pyrdacor** [comment]
@a1exh Yes such a check should be useful. And another check should test if the input files are UTF-8 encoded. Will add both soon.

**Comment by fuckgithub42** [comment]
The error I get is when using the keyword schwester.
![image](https://user-images.githubusercontent.com/88953552/132679835-9617c359-fdc7-4a1d-b141-1e78bd04ab54.png)

**Comment by Pyrdacor** [comment]
@fuckgithub42 @Winnetou11 Can you try with german 1.09 please? Was released today. You can use your version of Ambermoon.net.

**Comment by fuckgithub42** [comment]
That fixed the issue, good work.
