### ISSUE TITLE
2D Map Issue Thieves Hideout

### ISSUE THREAD

**Issue by Thallyrion** [Pyrdacor/Ambermoon.net#7]
Enter first floor of the Thieves Hideout. You can't leave. Stairs down don't work.

![thieves hideout 1st floor](https://user-images.githubusercontent.com/69513157/90511469-cd8c8280-e15c-11ea-8fc1-e90d4ecac808.png)

**Comment by Pyrdacor** [comment]
This also happens with the fire place in grandfathers house. Every map uses chained map events per tile. At the moment only the first one is executed. If the change map event is preceded by another event (e.g. a condition) it won't be triggered.

I will implement this later the day.

**Comment by Pyrdacor** [comment]
Ok I implemented map event chains and improved map events in general. But then I noticed it wasn't the problem. The stairs are just marked as "block movement". The problem is that each tile can have a back and a front tile. And if it has a front tile, this tile matters in regards of movement blocking etc. But some tiles have the front tile not blocking but are actual walls in the game. Those tiles have a blocking back tile so I thought it is blocking if either front or back tile blocks. And so I did it that way. But the stairs are a case were this isn't working so I reverted the logic to "only front tile matters if present". Have to research this again.

In v1.0.10 (which is coming in a minute) this should work. But there will be some tiles that won't block anymore even if they should. :(

**Comment by Thallyrion** [comment]
> In v1.0.10 (which is coming in a minute) this should work. But there will be some tiles that won't block anymore even if they should.

Indeed there are. I guess another way to determine the correct function of a tile has to be found.

![blocking problem](https://user-images.githubusercontent.com/69513157/90559578-0c8ef800-e19e-11ea-87ad-27cae0a65f05.png)

**Comment by Thallyrion** [comment]
Found another interesting case where the event still does not correctly work.  

Tested with 1.10 House of Healers Cellar stairs still don't work

![house of healers cellar](https://user-images.githubusercontent.com/69513157/90559939-a8b8ff00-e19e-11ea-87b0-bae8583aa226.png)

**Comment by Pyrdacor** [comment]
That's exactly the spot where I first that issue. There are not really bits left which can be the movement blocking flag. The only thing I can think of is a bit in the front tile data that says "get movement blocking from back tile". I will look into it the next days.

**Comment by Pyrdacor** [comment]
About the healer cellar: I will check tomorrow.

**Comment by Thallyrion** [comment]
Found another spot for this issue. Southern City House

![city house](https://user-images.githubusercontent.com/69513157/90560328-3694ea00-e19f-11ea-8f83-33598be10556.png)

**Comment by Pyrdacor** [comment]
The new cases might due to map borders. I restricted to move the player only until a 1 tile border is reached in indoor maps as it wouldn't make sense to move him to the edge of a map. At least I thought so. But now as I see the doors and stairs on the edge of the map this might have been a mistake. So I think I know how to fix this.

**Comment by Pyrdacor** [comment]
Should be fixed in v1.0.11.
